# Stage 1: Install dependencies and build the app
FROM node:18-alpine AS builder
WORKDIR /app

# Copy package.json and package-lock.json or yarn files
COPY package*.json ./

# Install dependencies
RUN pnpm install

# Copy the rest of your application code
COPY . .

# Build the Next.js app for production
RUN pnpm run build

# Stage 2: Create production image to run the app
FROM node:18-alpine AS runner
WORKDIR /app

# Install only production dependencies
COPY package*.json ./
RUN pnpm install --production

# Copy built Next.js files and public assets from builder stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/node_modules ./node_modules

# Expose port 3000
EXPOSE 3000

# Start the Next.js app
CMD ["pnpm", "start"]